---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: strimzi-topic-controller
  labels:
    app: strimzi
---
apiVersion: v1
kind: ClusterRole
metadata:
  name: strimzi-topic-controller-role
  labels:
    app: strimzi
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
---
apiVersion: v1
kind: RoleBinding
metadata:
  name: strimzi-topic-controller-binding
  labels:
    app: strimzi
subjects:
  - kind: ServiceAccount
    name: strimzi-topic-controller
roleRef:
  kind: ClusterRole
  name: strimzi-topic-controller-role
apiGroup: v1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: strimzi-topic-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: strimzi-topic-controller
    spec:
      serviceAccountName: strimzi-topic-controller
      containers:
        - name: strimzi-topic-controller
          image: scholzj/topic-controller:latest
          env:
            - name: STRIMZI_CONTROLLER_LABELS
              value: "app=strimzi,kind=topic" # TODO
            # specify the configmap name where to find the rest of the config
            - name: CONTROLLER_K8S_NAME
              value: topic-controller-config
---
# A configmap for configuring the topic controller
apiVersion: v1
kind: ConfigMap
metadata:
  name: topic-controller-config
data:
  #kafkaBootstrapServers: "${KAFKA_SERVICE_HOST}:${KAFKA_SERVICE_PORT}"
  #zookeeperConnect: "${KAFKA_ZOOKEEPER_SERVICE_HOST}:${KAFKA_ZOOKEEPER_SERVICE_PORT}"
  zookeeperSessionTimeout: 10 seconds
  fullReconciliationInterval: 2 hours
  reassignVerifyInterval: 30 seconds
