apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka-rejected-consumer
  name: kafka-rejected-consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-rejected-consumer
      annotations:
        topic-webhook.kafka.strimzi.io/topics: "[ {\"name\": \"i-do-not-exist-topic\", \"create\": false, \"assert\": false, \"partitions\": 3, \"replicas\": 3, \"config\": { \"cleanup.policy\": \"compact\" } } ]"
    spec:
      containers:
      - name: kafka-consumer
        image: scholzj/kafka-consumer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: kafka:9092
          - name: TOPIC
            value: i-do-not-exist-topic
          - name: GROUP_ID
            value: my-kafka-consumer