apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka-consumer
  name: kafka-producer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-consumer
      annotations:
        topic-webhook.kafka.strimzi.io/topics: "[ {\"name\": \"my-webhooked-topic\", \"create\": true, \"assert\": false, \"partitions\": 3, \"replicas\": 3, \"config\": { \"cleanup.policy\": \"compact\" } } ]"
    spec:
      containers:
      - name: kafka-producer
        image: scholzj/kafka-producer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: kafka:9092
          - name: TOPIC
            value: my-webhooked-topic
          - name: TIMER
            value: "10000"