apiVersion: v1
kind: ConfigMap
metadata:
  name: example-conflict-topic
  labels:
    app: strimzi
    kind: topic
data:
  name: example-conflict-topic
  partitions: "3"
  replicas: "1"
  config: '{ "cleanup.policy":"compact,delete", "retention.ms":"4600000" }'

